---
version: '3.4'
services:

  frontend:
    image: mattiariola/spg_frontend:latest
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      #Those env variable doesn't override the proxy address
      #HTTP_PROXY: "http://server:8080"
      #PROXY: "http://server:8080"

  server:
    image: mattiariola/spg_server:latest
    depends_on:
      - database
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/spg"
      server.port: 8080
      spring.datasource.username: root
      spring.datasource.password: password
    ports:
      - "8080:8080"
    
  database:
    image: mysql:5.7
    environment: &mysql-default-environment
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spg
      MYSQL_USER: asparago
      MYSQL_PASSWORD: asparago
    ports:
      - "3306:3306"
    # volumes:
      #- ./opt/script/data/initialization/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      # - mysql-persistent-volume:/var/lib/mysql

  database-test:    
    image: mysql:5.7
    environment: 
      *mysql-default-environment
    ports:
      - "13306:3306"
    
# volumes:
#   mysql-persistent-volume:
