---
version: "2"
services:
  # To test with MariaDB, set FLEET_MYSQL_IMAGE to mariadb:10.6 or the like.
  mysql:
    image: mysql:5.7
    container_name: db
    environment: &mysql-default-environment
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spg
      MYSQL_USER: asparago
      MYSQL_PASSWORD: asparago
    ports:
      - "3305:3306"
    volumes:
      - ./opt/script/data/initialization/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mysql-persistent-volume:/var/lib/mysql
  mysql_test:
    image: mysql:5.7
    container_name: test_db
    environment: *mysql-default-environment
    ports:
      - "3307:3306"
    volumes:
      - ./opt/script/data/initialization/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql-persistent-volume:
