name: Docker build a

on:
  push:
    branches:
    - main
    - githubworkflow-*

jobs:

  fe_docker_build_and_push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend/spg-frontend
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v5.6
      run: |
        docker build --tag mattiariola/spg_frontend:${{ GITHUB_REF_NAME }} .
        docker push mattiariola/spg_frontend:${{ GITHUB_REF_NAME }}
        
        
