name: Docker build a

on:
  push:
    branches:
    - main
    - githubworkflow-*

jobs:
  docker_build_and_push:
    name: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: FE Docker build
      run: docker build --tag mattiariola/spg_frontend:$GITHUB_REF_NAME /home/runner/work/SPG/Frontend/spg-frontend
    - name: Docker push
      run: docker push mattiariola/spg_frontend:$GITHUB_REF_NAME
        
        
