name: fe_sonarcloud
on:
  push:
    branches:
      - main
      - githubworkflow-*
      - spg-v*
      - FE/*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  fe_sonarcloud:
    name: fe_sonarcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
    # start infra dependencies
    - name: Start database conainer
      run: docker-compose up -d database database-test &
    
    # start server
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Start server
      run: mvn spring-boot:run -f ./server/SPG/pom.xml &

    # install npm dependencies
    - name: front end dependencies
      run: npm install --prefix ./Frontend/spg-frontend/
    
    # generate reports for sonarcloud
    - name: generate fe test report
      run: npm run --prefix ./Frontend/spg-frontend/ test:ci
    - name: generate fe coverage report
      run: npm run --prefix ./Frontend/spg-frontend/ coverage:ci

    # sonar 
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: Frontend/spg-frontend    
        args: >
          -Dsonar.organization=se2-group-p12
          -Dsonar.projectKey=FE_SPG
          -Dsonar.testExecutionReportPaths=reports/test-reporter.xml
          -Dsonar.sources=.
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.coverage.exclusions=**/*.test.js
          -Dsonar.projectName=SPG
          -Dsonar.projectVersion=1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.FE_SONAR_TOKEN }}
