name: dockerhub_release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  dockerhub_release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set tag output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: FE Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Frontend/spg-frontend
          push: true
          tags: mattiariola/spg_frontend:latest, mattiariola/spg_frontend:${{ steps.vars.outputs.tag }}
      -
        name: BE Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./server/SPG
          push: true
          tags: mattiariola/spg_server:latest, mattiariola/spg_server:${{ steps.vars.outputs.tag }}
